[tools]
go = "1.25"
"go:github.com/ynny-github/agent-sandbox/agent-sandbox" = "v0.7.0"
"go:github.com/ynny-github/taskgate/taskgate" = "v0.1.1"
lefthook = "latest"

[env]
# golang
GOMODCACHE = "{{config_root}}/.go/pkg/mod/cache"

# python
UV_CACHE_DIR = "{{config_root}}/.uv/cache"
