package claude

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/ynny-github/agent-sandbox/agent-sandbox/internal/policysnapshot"
)

// ShellEnvVar names the variable Claude Code reads to pick the shell it runs
// every Bash tool command with.
const ShellEnvVar = "CLAUDE_CODE_SHELL"

// shellWrapperScript renders the wrapper: a shell that is bash with two flags
// bolted on, and nothing else.
func shellWrapperScript(bashPath string) string {
	return "#!/bin/sh\n" +
		"# Generated by agent-sandbox at launch; safe to delete when no session runs.\n" +
		"exec " + bashPath + " --norc --noprofile \"$@\"\n"
}

// ShellWrapperPath returns the per-process path of the wrapper. The base name
// carries "bash" because Claude ignores CLAUDE_CODE_SHELL unless the path
// string contains "bash" or "zsh".
func ShellWrapperPath() (string, error) {
	dir, err := policysnapshot.StateDir()
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", fmt.Errorf("create state dir: %w", err)
	}
	return filepath.Join(dir, fmt.Sprintf("norc-bash-%d", os.Getpid())), nil
}

// writeShellWrapper writes the wrapper at path, delegating to bashPath.
func writeShellWrapper(path, bashPath string) error {
	if err := os.WriteFile(path, []byte(shellWrapperScript(bashPath)), 0o700); err != nil {
		return fmt.Errorf("write shell wrapper: %w", err)
	}
	return nil
}

// defaultShellWrapper writes the wrapper for this launch and returns its path
// plus a cleanup that removes it.
//
// bash is resolved on the host, at launch, rather than named in the profile:
// on a Nix-managed host its real path is content-addressed, so a path written
// down anywhere outlives exactly one package upgrade. Regenerating the file
// every launch is what keeps that staleness from ever mattering.
func defaultShellWrapper() (string, func(), error) {
	bashPath, err := exec.LookPath("bash")
	if err != nil {
		return "", nil, fmt.Errorf("locate bash for the agent's shell: %w", err)
	}
	path, err := ShellWrapperPath()
	if err != nil {
		return "", nil, err
	}
	if err := writeShellWrapper(path, bashPath); err != nil {
		return "", nil, err
	}
	return path, func() { os.Remove(path) }, nil
}
